### ISSUE TITLE
Include guard macro uses a reserved name

### ISSUE THREAD

**Issue by jwakely** [cnbatch/dynarray#2]
https://github.com/cnbatch/dynarray/blob/7d86b2f743d3edb1009d24953bab92539521b86c/dynarray.hpp#L55

`_VLA_DYNARRY_` is a reserved name, which makes this header undefined according to the standard. There's no reason you need a leading underscore for that macro, you can just use `VLA_DYNARRY` or `VLA_DYNARRY_HPP_INCLUDED` or something like that.

**Comment by cnbatch** [comment]
The macros have been updated to prevent the use of reserved names.

Thank you for your valuable suggestion!

**Comment by jwakely** [comment]
Nice, thanks!

**Comment by localspook** [comment]
Commit [d9189b4](https://github.com/cnbatch/dynarray/commit/d9189b4eb9009a4c1192ecdc861c3e079b011e7d) didn't fix the issue. The new names (for example, `_VLA_HEADER_DYNARRAY_HPP_`) still have leading underscores.

**Comment by jwakely** [comment]
Right, that's just as bad (I didn't check the actual code, just assumed what was said here was correct).

The problem is not that the names don't end in "HPP" it's that the start with an underscore followed by an uppercase letter. `_VLA_DYNARRAY` is bad, `VLA_DYNARRY` is good. If you want so use `XXX_HEADER_XXX_HPP` that's fine, but it can't use a leading underscore.

**Comment by cnbatch** [comment]
Truely sorry about that.
Please try the new version, I have now deleted the underscores at the beginning of the macros.
